name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          git config --global user.email "44930179+jhasuraj01@users.noreply.github.com"
          git config --global user.name "jhasuraj01"
          export GIT_USER=jhasuraj01:${{ secrets.GITHUBPAGES_DEPLOYMENT_TOKEN }}
          npm i
          npm run deploy
